name: flutter-starter
description: Starter Boilerplate.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  provider: ^4.0.4
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.7.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  url_launcher: ^5.4.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
